# Generated by Django 3.2 on 2021-11-13 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTag',
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='user.fuser', verbose_name='작성자'),
        ),
    ]
