# Generated by Django 3.2 on 2021-11-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('community', '0002_auto_20211113_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='user.Fuser'),
        ),
    ]
