# Generated by Django 3.2.5 on 2021-09-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='글 제목')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_del', models.BooleanField(default=False)),
                ('body', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='사진')),
                ('writer', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.fuser', verbose_name='작성자')),
            ],
        ),
    ]
