# Generated by Django 3.2.5 on 2021-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuser',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
